### PR TITLE
Add the Valguero map

### PR DESCRIPTION
**Pull request by Rottenbeer**

### CODE REVIEW

**Comment by kkm** [comment]
Can I get this download? thanks.

**Comment by Rottenbeer** [comment]
If the author does not merge it, I guess you need to compile it on your own.

**Comment by kkm** [comment]
Oh can someone compile then upload for me? please..I am not coder..

**Comment by sixokig** [comment]
> 
> 
> If the author does not merge it, I guess you need to compile it on your own.

I think the author lost interest in this project, he kept saying he'd update soon, but never did
Could you please release your binaries, and please add the improvements by jamckee

**Pull request closed without merging**
